server:
  port: 8080

speech:
  microsoft:
    subscription-key: G4rDKnpeQZ55GLXNkLsydemAdJERS8bhnWfgvM9JgkkwuOTWNI1RJQQJ99BCAC3pKaRXJ3w3AAAYACOGctDB
    region: eastasia
    recognition:
      language: ${MICROSOFT_RECOGNITION_LANGUAGE:zh-CN}
    synthesis:
      voice-name: ${MICROSOFT_VOICE_NAME:zh-CN-XiaoxiaoNeural}
      language: ${MICROSOFT_SYNTHESIS_LANGUAGE:zh-CN}
  
  openai:
    api-key: ${OPENAI_API_KEY:your-openai-api-key}
    model: ${OPENAI_MODEL:tts-1}
    voice: ${OPENAI_VOICE:alloy}
    speed: ${OPENAI_SPEED:1.0}

# 连接池配置
pool:
  # 最大闲置连接数
  max-idle: 8
  # 最小闲置连接数
  min-idle: 4
  # 最大连接数
  max-total: 16
  # 最大等待时间(毫秒)
  max-wait-millis: 1000

# 调试配置
debug:
  audio:
    # 是否将音频数据保存到文件
    save-to-file: ${DEBUG_SAVE_AUDIO:false}
    # 音频文件保存目录
    directory: ${DEBUG_AUDIO_DIR:./debug-audio}

logging:
  level:
    com.translation.system: DEBUG
    org.springframework.web.socket: INFO 